api/urls.py
from django.urls import path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from . import api

urlpatterns = [
    path('users', api.UserList.as_view(), name='users'),
    path('profile', api.UserDetail.as_view(), name='profile'),
    path('schema', SpectacularAPIView.as_view(), name='schema'),
    path('schema/swagger-ui', SpectacularSwaggerView.as_view(url_name='api:schema'), name='swagger-ui'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('chat/', include(('chat.urls', 'chat'), namespace='chat')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

registration_patterns = ([
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutRedirectView.as_view(), name='logout'),
], 'registration')

profile_patterns = ([
    path('', views.ProfileRedirectView.as_view(), name='own'),
    path('list', views.UserListView.as_view(), name='list'),
    path('<int:pk>', views.ProfileView.as_view(), name='detail'),
    path('edit', views.ProfileEditView.as_view(), name='edit'),
    path('notification/read/<int:notif_id>', views.NotificationReadView.as_view(), name='notification_read'),
    path('notification/unread/<int:notif_id>', views.NotificationUnreadView.as_view(), name='notification_unread'),
    path('notification/delete/<int:notif_id>', views.NotificationDeleteView.as_view(), name='notification_delete'),
], 'profile')

course_patterns = ([
    path('', views.CourseListView.as_view(), name='list'),
    path('create', views.CourseCreateView.as_view(), name='create'),
    path('<int:pk>', views.CourseView.as_view(), name='detail'),
    path('<int:pk>/enroll', views.CourseEnrollView.as_view(), name='enroll'),
    path('<int:pk>/feedback/add', views.CourseFeedbackAddView.as_view(), name='feedback_add'),
    path('<int:pk>/material/add', views.CourseMaterialAddView.as_view(), name='material_add'),
    path('<int:pk>/student/block/<int:student_id>', views.CourseStudentBlockView.as_view(), name='student_block'),
    path('<int:pk>/student/unblock/<int:student_id>', views.CourseStudentUnblockView.as_view(), name='student_unblock'),
], 'course')

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('', include(registration_patterns)),
    path('profile/', include(profile_patterns)),
    path('course/', include(course_patterns)),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    status = models.CharField(max_length=100, blank=True)
    bio = models.TextField(max_length=500, blank=True)
    company = models.CharField(max_length=100, blank=True)
    avatar = models.ImageField(upload_to='main/profile/avatars/', blank=True, null=True)
    last_request = models.DateTimeField(auto_now_add=True)

class Course(models.Model):
    name = models.CharField(max_length=100)
    students = models.ManyToManyField(User, related_name='courses')
    blocked_students = models.ManyToManyField(User, related_name='blocked_courses')
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='courses_taught')
    description = models.TextField(max_length=1000)

    def __str__(self):
        return self.name

class CourseFeedback(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='feedbacks')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='feedbacks')
    grade = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    comment = models.TextField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

class CourseMaterial(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='materials')
    file = models.FileField(upload_to='main/course/materials/')
    name = models.CharField(max_length=200)
    uploaded_at = models.DateTimeField(auto_now_add=True)

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notifications')
    text = models.TextField()
    link = models.CharField(max_length=200)
    read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

main/forms.py
from django import forms
from django.forms import TextInput, PasswordInput
from django.contrib.auth.forms import UserCreationForm
from .models import *

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'status', 'bio', 'company', 'avatar')

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('name', 'description')

class CourseFeedbackForm(forms.ModelForm):
    class Meta:
        model = CourseFeedback
        fields = ('grade', 'comment')

class CourseMaterialForm(forms.ModelForm):
    class Meta:
        model = CourseMaterial
        fields = ('name', 'file',)

main/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.models import Group
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import TemplateView, DetailView, ListView, RedirectView, CreateView, UpdateView
from .forms import *

class IndexView(TemplateView):
    template_name = 'main/index.html'

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('profile:own')
        return super().get(request)

class UserListView(UserPassesTestMixin, ListView):
    model = User
    template_name = 'profile/list.html'

    def test_func(self):
        return self.request.user.groups.filter(name='Teachers').exists()

    # Filter users by group specified in the URL
    def get_queryset(self):
        queryset = super().get_queryset()
        group_name = self.request.GET.get('group')
        if group_name:
            group = Group.objects.get(name=group_name)
            queryset = queryset.filter(groups__in=[group])
        return queryset

class SignupView(TemplateView, UserPassesTestMixin):
    template_name = 'registration/signup.html'

    def get(self, request):
        if (self.request.user.is_authenticated):
            return redirect('profile:own')
            
        form = SignupForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = SignupForm(request.POST)

        if form.is_valid():
            user = form.save()

            # Add user to Student group
            student_group = Group.objects.get(name='Students')
            student_group.user_set.add(user)

            # Log the user in
            login(request, user)
            return redirect('profile:own')

        return render(request, self.template_name, 
            {'form': form})

class LogoutRedirectView(RedirectView):
    def get(self, request):
        logout(request)
        self.url = reverse('index')
        print(self.url)
        return super().get(request)

# Redirect to the user's profile page
class ProfileRedirectView(LoginRequiredMixin, RedirectView):
    def get(self, request):
        self.url = reverse('profile:detail', kwargs={'pk': request.user.id})
        return super().get(request)

class ProfileView(DetailView):
    model = User
    template_name = 'profile/detail.html'

class ProfileEditView(LoginRequiredMixin, TemplateView):
    template_name = 'profile/edit.html'

    def get(self, request):
        form = ProfileForm(instance=request.user)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = ProfileForm(request.POST, request.FILES, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect ('profile:own')

        # If form is not valid, re-render the page with the form
        return render(request, self.template_name, {'form': form})

class CourseListView(ListView):
    model = Course
    template_name = 'course/list.html'

class CourseView(DetailView):
    model = Course
    template_name = 'course/detail.html'

class CourseCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Course
    template_name = 'course/create.html'
    form_class = CourseForm

    def test_func(self):
        return self.request.user.groups.filter(name='Teachers').exists()

    # form_valid is called when the form is submitted and valid
    def form_valid(self, form):
        form.instance.teacher = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('course:detail', kwargs={'pk': self.object.pk})

class CourseEnrollView(LoginRequiredMixin, UserPassesTestMixin, RedirectView):
    def test_func(self):
        course = Course.objects.get(pk=self.kwargs['pk'])
        is_blocked = self.request.user in course.blocked_students.all()
        is_teacher = self.request.user == course.teacher
        return not is_blocked and not is_teacher

    def get_redirect_url(self, *args, **kwargs):
        course = Course.objects.get(pk=self.kwargs['pk'])
        course.students.add(self.request.user)
        Notification.objects.create(
            user=course.teacher,
            text=f'{self.request.user} enrolled in {course.name}',
            link=reverse('course:detail', kwargs={'pk': course.pk}))

        return reverse('course:detail', kwargs={'pk': self.kwargs['pk']})

class CourseFeedbackAddView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = CourseFeedback
    template_name = 'course/feedback/add.html'
    form_class = CourseFeedbackForm

    def test_func(self):
        course = Course.objects.get(pk=self.kwargs['pk'])
        is_enrolled = self.request.user in course.students.all()
        has_feedback = course.feedbacks.filter(author=self.request.user).exists()
        return is_enrolled and not has_feedback

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.course = Course.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('course:detail', kwargs={'pk': self.object.course.pk})

class CourseMaterialAddView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = CourseMaterial
    template_name = 'course/material/add.html'
    form_class = CourseMaterialForm

    def test_func(self):
        course = Course.objects.get(pk=self.kwargs['pk'])
        return self.request.user == course.teacher

    def form_valid(self, form):
        form.instance.course = Course.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        # Notify each student enrolled in the course
        course = Course.objects.get(pk=self.kwargs['pk'])
        for student in course.students.all():
            Notification.objects.create(
                user=student,
                text=f'New material in {course.name}',
                link=reverse('course:detail', kwargs={'pk': course.pk}))

        return reverse('course:detail', kwargs={'pk': self.kwargs['pk']})

class CourseStudentBlockView(LoginRequiredMixin, UserPassesTestMixin, RedirectView):
    def test_func(self):
        course = Course.objects.get(pk=self.kwargs['pk'])
        return self.request.user == course.teacher

    def get_redirect_url(self, *args, **kwargs):
        course = Course.objects.get(pk=self.kwargs['pk'])
        student = get_object_or_404(User, id=kwargs['student_id'])

        course.students.remove(student)
        course.blocked_students.add(student)

        return reverse('course:detail', kwargs={'pk': self.kwargs['pk']})

class CourseStudentUnblockView(LoginRequiredMixin, UserPassesTestMixin, RedirectView):
    def test_func(self):
        course = Course.objects.get(pk=self.kwargs['pk'])
        return self.request.user == course.teacher

    def get_redirect_url(self, *args, **kwargs):
        course = Course.objects.get(pk=self.kwargs['pk'])
        student = get_object_or_404(User, id=kwargs['student_id'])

        course.students.add(student)
        course.blocked_students.remove(student)

        return reverse('course:detail', kwargs={'pk': self.kwargs['pk']})

class NotificationReadView(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        notification = get_object_or_404(Notification, id=kwargs['notif_id'])
        notification.read = True
        notification.save()
        return reverse('profile:own') + '#notifications'

class NotificationDeleteView(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        notification = get_object_or_404(Notification, id=kwargs['notif_id'])
        notification.delete()
        return reverse('profile:own') + '#notifications'

class NotificationUnreadView(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        notification = get_object_or_404(Notification, id=kwargs['notif_id'])
        notification.read = False
        notification.save()
        return reverse('profile:own') + '#notifications'

main/templates/profile/detail.html
{% extends "base.html" %}
{% load main_tags %}

{% block content %}
<div class="md:flex mx-20 my-20">

    <!-- Left Column -->
    <div class="md:w-2/5 md:mx-5 mb-10">
        <div class="flex items-center gap-4">
            <div class="w-36 h-36 relative inline-flex items-center justify-center overflow-hidden bg-gray-100 rounded-full dark:bg-gray-600">
                {% if user.avatar %}
                    <img src="{{ user.avatar.url }}" alt="{{ user.username }}'s avatar">
                {% else %}
                    <span class="text-5xl font-medium text-gray-600 dark:text-gray-300 uppercase">{% get_initials user %}</span>
                {% endif %}
            </div>  
            <div class="font-medium dark:text-white ml-1">
                <div>
                    {% displayname user %}
                    {% if user.first_name or user.last_name %}
                        <span class="text-sm text-gray-500 dark:text-gray-400 font-normal"> ({{ user.username }})</span>
                    {% endif %}
                </div>
                <div class="text-sm text-gray-500 dark:text-gray-400">Joined in {{ user.date_joined|date:"F Y" }}</div>
                <div class="mt-5 italic text-sm text-gray-500 dark:text-gray-400"> {{ user.status }}</div>
            </div>
        </div>

        <dl class="max-w-md text-gray-900 divide-y divide-gray-200 dark:text-white dark:divide-gray-700 mt-10">
            <div class="flex flex-col pb-3 mb-3">
                <dt class="mb-1 text-gray-500 md:text-sm dark:text-gray-400">Bio</dt>
                <dd class="text-sm text-justify font-normal">
                    {% if user.bio %}
                        {{ user.bio }}
                    {% else %}
                        -
                    {% endif %}
                </dd>
            </div>
            <div class="flex flex-col pb-3 mb-1">
                <dt class="mt-1 mb-1 text-gray-500 md:text-sm dark:text-gray-400">Email</dt>
                <dd class="text-sm font-medium">
                    {% if user.email %}
                        <a href="mailto:{{ user.email }}">{{ user.email }}</a>
                    {% else %}
                        -
                    {% endif %}
                </dd>
            </div>
            <div class="flex flex-col pb-3">
                <dt class="mt-1 mb-1 text-gray-500 md:text-sm dark:text-gray-400">Company</dt>
                <dd class="text-sm font-medium">
                    {% if user.company %}
                        {{ user.company }}
                    {% else %}
                        -
                    {% endif %}
                </dd>
            </div>
        </dl>
        <div class="mt-5">
            {% if user == request.user %}
                <a class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" href="{% url 'profile:edit' %}">Edit Profile</a>
                <a class="font-normal text-sm text-blue-600 dark:text-blue-500 hover:underline" href="{% url 'api:profile' %}">Export Data</a>
            {% endif %}
        </div>
    </div>

    <!-- Right column -->
    <div class="md:w-3/5 md:ml-20">
        <div>
            {% include './user_courses.html' %}
        </div>
        <div id="notifications" class="mt-10">
            {% if user == request.user %}
                {% include './notifications.html' %}
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}

main/templates/profile/edit.html
{% extends "base.html" %}
{% load main_tags %}

{% block content %}
<div class="md:flex mx-20 my-20">
    <!-- Left Column -->
    <div class="md:w-2/5 md:mx-5 mb-10">
        <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="flex items-center gap-4">
            <label for="dropzone-file" class="flex flex-col items-center justify-center w-36 h-36 rounded-full border-2 border-gray-300 border-dashed cursor-pointer bg-gray-50 dark:hover:bg-bray-800 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600">
                <div class="flex flex-col items-center justify-center pt-5 pb-6">
                    <svg class="w-7 h-7 mb-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 16">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 13h3a3 3 0 0 0 0-6h-.025A5.56 5.56 0 0 0 16 6.5 5.5 5.5 0 0 0 5.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 0 0 0 8h2.167M10 15V6m0 0L8 8m2-2 2 2"/>
                    </svg>
                    <p class="mb-2 text-sm text-gray-500 dark:text-gray-400"><span class="font-semibold">Change Avatar</span></p>
                </div>
                <input name="{{ form.avatar.html_name }}" id="dropzone-file" type="file" class="hidden" />
            </label>
            <div class="font-normal dark:text-white ml-1">
                <div>
                    <label class="mb-1 text-gray-500 md:text-sm dark:text-gray-400 mt-1">First Name</label>
                    <input name="{{ form.first_name.html_name }}" type="text" value="{{ user.first_name }}" class="mb-2 block w-full p-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 text-xs focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">

                    <label class="mb-1 text-gray-500 md:text-sm dark:text-gray-400 mt-2">Last Name</label>
                    <input name="{{ form.last_name.html_name }}" type="text" value="{{ user.last_name }}" class="mb-2 block w-full p-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 text-xs focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                    
                </div>
                <div class="mt-5">
                    <label class="mb-1 text-gray-500 md:text-sm dark:text-gray-400 mt-2">Status</label>
                    <textarea name="{{ form.status.html_name }}" rows="2" class="block font-normal p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">{{ user.status }}</textarea>
                    {% if form.errors.status %}
                        <p class="mt-1 text-sm text-red-600 dark:text-red-500 font-medium">Text is too long! (Max 100 char.)</p>
                    {% else %}
                        <p class="mt-1 text-sm text-gray-500 dark:text-gray-400 font-normal">Max 100 characters</p>
                    {% endif %}
                </div>
            </div>
        </div>

        <dl class="max-w-md text-gray-900 divide-y divide-gray-200 dark:text-white dark:divide-gray-700 mt-10">
            <div class="flex flex-col pb-3 mb-3">
                <dt class="mb-1 text-gray-500 md:text-sm dark:text-gray-400">Bio</dt>
                <dd class="text-sm text-justify font-normal">
                    <textarea name="{{ form.bio.html_name }}" rows="4" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">{{ user.bio }}</textarea>
                    {% if form.errors.status %}
                        <p class="mt-1 text-sm text-red-600 dark:text-red-500 font-medium">Text is too long! (Max 500 char.)</p>
                    {% else %}
                        <p class="mt-1 text-sm text-gray-500 dark:text-gray-400 font-normal">Max 500 characters</p>
                    {% endif %}
                </dd>
            </div>
            <div class="flex flex-col pb-3 mb-1">
                <dt class="mt-1 mb-1 text-gray-500 md:text-sm dark:text-gray-400">Email</dt>
                <dd class="text-sm font-normal">
                    <input name="{{ form.email.html_name }}" value="{{ user.email }}" type="email" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                </dd>
            </div>
            <div class="flex flex-col pb-3">
                <dt class="mt-1 mb-1 text-gray-500 md:text-sm dark:text-gray-400">Company</dt>
                <dd class="text-sm font-normal">
                    <input name="{{ form.company.html_name }}" value="{{ user.company }}" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                    {% if form.errors.status %}
                        <p class="mt-1 text-sm text-red-600 dark:text-red-500 font-medium">Text is too long! (Max 100 char.)</p>
                    {% else %}
                        <p class="mt-1 text-sm text-gray-500 dark:text-gray-400 font-normal">Max 100 characters</p>
                    {% endif %}
                </dd>
            </div>
        </dl>
        <div class="mt-5">
            <input type="submit" value="Save" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"/>
        </div>
      </form>
    </div>
    
    <!-- Right column -->
    <div class="md:w-3/5 md:ml-20">
        {% include './user_courses.html' %}
    </div>

{% endblock %}

main/templates/profile/list.html
{% extends "base.html" %}
{% load main_tags %}

{% block content %}

<div class="container mt-4 max-w-sm mx-auto">
<form method="get">
   <button class="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" name="group" value="" onchange="this.form.submit()">All</button>
   <button class="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" name="group" value="Students" onchange="this.form.submit()">Students</button>
   <button class="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" name="group" value="Teachers" onchange="this.form.submit()">Teachers</button>
</form>

<ul class="max-w-md divide-y divide-gray-200 dark:divide-gray-700">
    {% for user in user_list %}
    <li class="py-3 sm:py-4 text-gray-500 rounded-lg hover:text-gray-900 hover:bg-gray-100 dark:text-gray-400 dark:bg-gray-800 dark:hover:bg-gray-700 dark:hover:text-white">
        <a href="{% url 'profile:detail' user.id %}">
        <div class="flex items-center space-x-4 rtl:space-x-reverse">
          <div class="flex-shrink-0">
            {% include 'avatar.html' %}
          </div>
          <div class="flex-1 min-w-0">
             <p class="text-sm font-medium text-gray-900 truncate dark:text-white">
                {% displayname user %}
             </p>
             <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                {% displayrole user %}
             </p>
          </div>
          <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
            {% if user|is_online %}
               <span class="bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-green-900 dark:text-green-300">Online</span>
            {% else %}
               <span class="bg-red-100 text-red-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded-full dark:bg-red-900 dark:text-red-300">Offline</span>
            {% endif %}
          </div>
        </div>
    </a>
    </li>
    {% endfor %}
 </ul>
</div>
{% endblock %}